repos:
-   repo: local
    hooks:
    -   id: clean-jupyer
        name: remove jupyer outputs and metadata
        files: \.ipynb$
        language: system
        entry: meta/tools.py
        args:
        - clean

    -   id: update-readme
        name: sync TOC in README.md
        files: \.ipynb$
        language: system
        entry: meta/tools.py
        args:
        - list-of-workshops-readme


    -   id: add-badges
        name: update 'open in colab' badges
        files: \.ipynb$
        language: system
        entry: meta/tools.py
        args:
        - badge

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: check-added-large-files
        args: ['--maxkb=500']

-   repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
    -   id: black-jupyter
        name: format jupyter notebooks with black
        args:
        - --line-length
        - "100"

# -   repo: local
#     hooks:
#     -   id: jupyer-strip-unnecessary
#         name: jupyter-strip-unnecessary
#         files: \.ipynb$
#         language: system
#         pass_filenames: true
#         entry: meta/clean-jupyter.sh
