repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: check-added-large-files
        args: ['--maxkb=500']
-   repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
    -   id: black-jupyter
        args:
        - --line-length
        - "100"
-   repo: local
    hooks:
    -   id: jupyer-strip-unnecessary
        name: jupyter-strip-unnecessary
        files: \.ipynb$
        language: system
        pass_filenames: true
        entry: meta/clean-jupyter.sh
